version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: Pay_Wage_DB
    restart: always

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: Pay_Wage_DB

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: Pay_Wage_DB
    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/Pay_Wage_DB

    command: sh -c "npx prisma generate && npm run start:prod"

volumes:
  postgres_data: